// Generated by /home/naomi/Work/tls-router/tlsproto/./genciphers.py
package tlsproto

import "fmt"

type CipherSuite uint16

const (
	CipherTlsNullWithNullNull                     = CipherSuite(0x0000)
	CipherTlsRsaWithNullMd5                       = CipherSuite(0x0001)
	CipherTlsRsaWithNullSha                       = CipherSuite(0x0002)
	CipherTlsRsaExportWithRc440Md5                = CipherSuite(0x0003)
	CipherTlsRsaWithRc4128Md5                     = CipherSuite(0x0004)
	CipherTlsRsaWithRc4128Sha                     = CipherSuite(0x0005)
	CipherTlsRsaExportWithRc2Cbc40Md5             = CipherSuite(0x0006)
	CipherTlsRsaWithIdeaCbcSha                    = CipherSuite(0x0007)
	CipherTlsRsaExportWithDes40CbcSha             = CipherSuite(0x0008)
	CipherTlsRsaWithDesCbcSha                     = CipherSuite(0x0009)
	CipherTlsRsaWith3desEdeCbcSha                 = CipherSuite(0x000a)
	CipherTlsDhDssExportWithDes40CbcSha           = CipherSuite(0x000b)
	CipherTlsDhDssWithDesCbcSha                   = CipherSuite(0x000c)
	CipherTlsDhDssWith3desEdeCbcSha               = CipherSuite(0x000d)
	CipherTlsDhRsaExportWithDes40CbcSha           = CipherSuite(0x000e)
	CipherTlsDhRsaWithDesCbcSha                   = CipherSuite(0x000f)
	CipherTlsDhRsaWith3desEdeCbcSha               = CipherSuite(0x0010)
	CipherTlsDheDssExportWithDes40CbcSha          = CipherSuite(0x0011)
	CipherTlsDheDssWithDesCbcSha                  = CipherSuite(0x0012)
	CipherTlsDheDssWith3desEdeCbcSha              = CipherSuite(0x0013)
	CipherTlsDheRsaExportWithDes40CbcSha          = CipherSuite(0x0014)
	CipherTlsDheRsaWithDesCbcSha                  = CipherSuite(0x0015)
	CipherTlsDheRsaWith3desEdeCbcSha              = CipherSuite(0x0016)
	CipherTlsDhAnonExportWithRc440Md5             = CipherSuite(0x0017)
	CipherTlsDhAnonWithRc4128Md5                  = CipherSuite(0x0018)
	CipherTlsDhAnonExportWithDes40CbcSha          = CipherSuite(0x0019)
	CipherTlsDhAnonWithDesCbcSha                  = CipherSuite(0x001a)
	CipherTlsDhAnonWith3desEdeCbcSha              = CipherSuite(0x001b)
	CipherTlsKrb5WithDesCbcSha                    = CipherSuite(0x001e)
	CipherTlsKrb5With3desEdeCbcSha                = CipherSuite(0x001f)
	CipherTlsKrb5WithRc4128Sha                    = CipherSuite(0x0020)
	CipherTlsKrb5WithIdeaCbcSha                   = CipherSuite(0x0021)
	CipherTlsKrb5WithDesCbcMd5                    = CipherSuite(0x0022)
	CipherTlsKrb5With3desEdeCbcMd5                = CipherSuite(0x0023)
	CipherTlsKrb5WithRc4128Md5                    = CipherSuite(0x0024)
	CipherTlsKrb5WithIdeaCbcMd5                   = CipherSuite(0x0025)
	CipherTlsKrb5ExportWithDesCbc40Sha            = CipherSuite(0x0026)
	CipherTlsKrb5ExportWithRc2Cbc40Sha            = CipherSuite(0x0027)
	CipherTlsKrb5ExportWithRc440Sha               = CipherSuite(0x0028)
	CipherTlsKrb5ExportWithDesCbc40Md5            = CipherSuite(0x0029)
	CipherTlsKrb5ExportWithRc2Cbc40Md5            = CipherSuite(0x002a)
	CipherTlsKrb5ExportWithRc440Md5               = CipherSuite(0x002b)
	CipherTlsPskWithNullSha                       = CipherSuite(0x002c)
	CipherTlsDhePskWithNullSha                    = CipherSuite(0x002d)
	CipherTlsRsaPskWithNullSha                    = CipherSuite(0x002e)
	CipherTlsRsaWithAes128CbcSha                  = CipherSuite(0x002f)
	CipherTlsDhDssWithAes128CbcSha                = CipherSuite(0x0030)
	CipherTlsDhRsaWithAes128CbcSha                = CipherSuite(0x0031)
	CipherTlsDheDssWithAes128CbcSha               = CipherSuite(0x0032)
	CipherTlsDheRsaWithAes128CbcSha               = CipherSuite(0x0033)
	CipherTlsDhAnonWithAes128CbcSha               = CipherSuite(0x0034)
	CipherTlsRsaWithAes256CbcSha                  = CipherSuite(0x0035)
	CipherTlsDhDssWithAes256CbcSha                = CipherSuite(0x0036)
	CipherTlsDhRsaWithAes256CbcSha                = CipherSuite(0x0037)
	CipherTlsDheDssWithAes256CbcSha               = CipherSuite(0x0038)
	CipherTlsDheRsaWithAes256CbcSha               = CipherSuite(0x0039)
	CipherTlsDhAnonWithAes256CbcSha               = CipherSuite(0x003a)
	CipherTlsRsaWithNullSha256                    = CipherSuite(0x003b)
	CipherTlsRsaWithAes128CbcSha256               = CipherSuite(0x003c)
	CipherTlsRsaWithAes256CbcSha256               = CipherSuite(0x003d)
	CipherTlsDhDssWithAes128CbcSha256             = CipherSuite(0x003e)
	CipherTlsDhRsaWithAes128CbcSha256             = CipherSuite(0x003f)
	CipherTlsDheDssWithAes128CbcSha256            = CipherSuite(0x0040)
	CipherTlsRsaWithCamellia128CbcSha             = CipherSuite(0x0041)
	CipherTlsDhDssWithCamellia128CbcSha           = CipherSuite(0x0042)
	CipherTlsDhRsaWithCamellia128CbcSha           = CipherSuite(0x0043)
	CipherTlsDheDssWithCamellia128CbcSha          = CipherSuite(0x0044)
	CipherTlsDheRsaWithCamellia128CbcSha          = CipherSuite(0x0045)
	CipherTlsDhAnonWithCamellia128CbcSha          = CipherSuite(0x0046)
	CipherTlsDheRsaWithAes128CbcSha256            = CipherSuite(0x0067)
	CipherTlsDhDssWithAes256CbcSha256             = CipherSuite(0x0068)
	CipherTlsDhRsaWithAes256CbcSha256             = CipherSuite(0x0069)
	CipherTlsDheDssWithAes256CbcSha256            = CipherSuite(0x006a)
	CipherTlsDheRsaWithAes256CbcSha256            = CipherSuite(0x006b)
	CipherTlsDhAnonWithAes128CbcSha256            = CipherSuite(0x006c)
	CipherTlsDhAnonWithAes256CbcSha256            = CipherSuite(0x006d)
	CipherTlsRsaWithCamellia256CbcSha             = CipherSuite(0x0084)
	CipherTlsDhDssWithCamellia256CbcSha           = CipherSuite(0x0085)
	CipherTlsDhRsaWithCamellia256CbcSha           = CipherSuite(0x0086)
	CipherTlsDheDssWithCamellia256CbcSha          = CipherSuite(0x0087)
	CipherTlsDheRsaWithCamellia256CbcSha          = CipherSuite(0x0088)
	CipherTlsDhAnonWithCamellia256CbcSha          = CipherSuite(0x0089)
	CipherTlsPskWithRc4128Sha                     = CipherSuite(0x008a)
	CipherTlsPskWith3desEdeCbcSha                 = CipherSuite(0x008b)
	CipherTlsPskWithAes128CbcSha                  = CipherSuite(0x008c)
	CipherTlsPskWithAes256CbcSha                  = CipherSuite(0x008d)
	CipherTlsDhePskWithRc4128Sha                  = CipherSuite(0x008e)
	CipherTlsDhePskWith3desEdeCbcSha              = CipherSuite(0x008f)
	CipherTlsDhePskWithAes128CbcSha               = CipherSuite(0x0090)
	CipherTlsDhePskWithAes256CbcSha               = CipherSuite(0x0091)
	CipherTlsRsaPskWithRc4128Sha                  = CipherSuite(0x0092)
	CipherTlsRsaPskWith3desEdeCbcSha              = CipherSuite(0x0093)
	CipherTlsRsaPskWithAes128CbcSha               = CipherSuite(0x0094)
	CipherTlsRsaPskWithAes256CbcSha               = CipherSuite(0x0095)
	CipherTlsRsaWithSeedCbcSha                    = CipherSuite(0x0096)
	CipherTlsDhDssWithSeedCbcSha                  = CipherSuite(0x0097)
	CipherTlsDhRsaWithSeedCbcSha                  = CipherSuite(0x0098)
	CipherTlsDheDssWithSeedCbcSha                 = CipherSuite(0x0099)
	CipherTlsDheRsaWithSeedCbcSha                 = CipherSuite(0x009a)
	CipherTlsDhAnonWithSeedCbcSha                 = CipherSuite(0x009b)
	CipherTlsRsaWithAes128GcmSha256               = CipherSuite(0x009c)
	CipherTlsRsaWithAes256GcmSha384               = CipherSuite(0x009d)
	CipherTlsDheRsaWithAes128GcmSha256            = CipherSuite(0x009e)
	CipherTlsDheRsaWithAes256GcmSha384            = CipherSuite(0x009f)
	CipherTlsDhRsaWithAes128GcmSha256             = CipherSuite(0x00a0)
	CipherTlsDhRsaWithAes256GcmSha384             = CipherSuite(0x00a1)
	CipherTlsDheDssWithAes128GcmSha256            = CipherSuite(0x00a2)
	CipherTlsDheDssWithAes256GcmSha384            = CipherSuite(0x00a3)
	CipherTlsDhDssWithAes128GcmSha256             = CipherSuite(0x00a4)
	CipherTlsDhDssWithAes256GcmSha384             = CipherSuite(0x00a5)
	CipherTlsDhAnonWithAes128GcmSha256            = CipherSuite(0x00a6)
	CipherTlsDhAnonWithAes256GcmSha384            = CipherSuite(0x00a7)
	CipherTlsPskWithAes128GcmSha256               = CipherSuite(0x00a8)
	CipherTlsPskWithAes256GcmSha384               = CipherSuite(0x00a9)
	CipherTlsDhePskWithAes128GcmSha256            = CipherSuite(0x00aa)
	CipherTlsDhePskWithAes256GcmSha384            = CipherSuite(0x00ab)
	CipherTlsRsaPskWithAes128GcmSha256            = CipherSuite(0x00ac)
	CipherTlsRsaPskWithAes256GcmSha384            = CipherSuite(0x00ad)
	CipherTlsPskWithAes128CbcSha256               = CipherSuite(0x00ae)
	CipherTlsPskWithAes256CbcSha384               = CipherSuite(0x00af)
	CipherTlsPskWithNullSha256                    = CipherSuite(0x00b0)
	CipherTlsPskWithNullSha384                    = CipherSuite(0x00b1)
	CipherTlsDhePskWithAes128CbcSha256            = CipherSuite(0x00b2)
	CipherTlsDhePskWithAes256CbcSha384            = CipherSuite(0x00b3)
	CipherTlsDhePskWithNullSha256                 = CipherSuite(0x00b4)
	CipherTlsDhePskWithNullSha384                 = CipherSuite(0x00b5)
	CipherTlsRsaPskWithAes128CbcSha256            = CipherSuite(0x00b6)
	CipherTlsRsaPskWithAes256CbcSha384            = CipherSuite(0x00b7)
	CipherTlsRsaPskWithNullSha256                 = CipherSuite(0x00b8)
	CipherTlsRsaPskWithNullSha384                 = CipherSuite(0x00b9)
	CipherTlsRsaWithCamellia128CbcSha256          = CipherSuite(0x00ba)
	CipherTlsDhDssWithCamellia128CbcSha256        = CipherSuite(0x00bb)
	CipherTlsDhRsaWithCamellia128CbcSha256        = CipherSuite(0x00bc)
	CipherTlsDheDssWithCamellia128CbcSha256       = CipherSuite(0x00bd)
	CipherTlsDheRsaWithCamellia128CbcSha256       = CipherSuite(0x00be)
	CipherTlsDhAnonWithCamellia128CbcSha256       = CipherSuite(0x00bf)
	CipherTlsRsaWithCamellia256CbcSha256          = CipherSuite(0x00c0)
	CipherTlsDhDssWithCamellia256CbcSha256        = CipherSuite(0x00c1)
	CipherTlsDhRsaWithCamellia256CbcSha256        = CipherSuite(0x00c2)
	CipherTlsDheDssWithCamellia256CbcSha256       = CipherSuite(0x00c3)
	CipherTlsDheRsaWithCamellia256CbcSha256       = CipherSuite(0x00c4)
	CipherTlsDhAnonWithCamellia256CbcSha256       = CipherSuite(0x00c5)
	CipherTlsSm4GcmSm3                            = CipherSuite(0x00c6)
	CipherTlsSm4CcmSm3                            = CipherSuite(0x00c7)
	CipherTlsEmptyRenegotiationInfoScsv           = CipherSuite(0x00ff)
	CipherTlsAes128GcmSha256                      = CipherSuite(0x1301)
	CipherTlsAes256GcmSha384                      = CipherSuite(0x1302)
	CipherTlsChacha20Poly1305Sha256               = CipherSuite(0x1303)
	CipherTlsAes128CcmSha256                      = CipherSuite(0x1304)
	CipherTlsAes128Ccm8Sha256                     = CipherSuite(0x1305)
	CipherTlsAegis256Sha512                       = CipherSuite(0x1306)
	CipherTlsAegis128lSha256                      = CipherSuite(0x1307)
	CipherTlsFallbackScsv                         = CipherSuite(0x5600)
	CipherTlsEcdhEcdsaWithNullSha                 = CipherSuite(0xc001)
	CipherTlsEcdhEcdsaWithRc4128Sha               = CipherSuite(0xc002)
	CipherTlsEcdhEcdsaWith3desEdeCbcSha           = CipherSuite(0xc003)
	CipherTlsEcdhEcdsaWithAes128CbcSha            = CipherSuite(0xc004)
	CipherTlsEcdhEcdsaWithAes256CbcSha            = CipherSuite(0xc005)
	CipherTlsEcdheEcdsaWithNullSha                = CipherSuite(0xc006)
	CipherTlsEcdheEcdsaWithRc4128Sha              = CipherSuite(0xc007)
	CipherTlsEcdheEcdsaWith3desEdeCbcSha          = CipherSuite(0xc008)
	CipherTlsEcdheEcdsaWithAes128CbcSha           = CipherSuite(0xc009)
	CipherTlsEcdheEcdsaWithAes256CbcSha           = CipherSuite(0xc00a)
	CipherTlsEcdhRsaWithNullSha                   = CipherSuite(0xc00b)
	CipherTlsEcdhRsaWithRc4128Sha                 = CipherSuite(0xc00c)
	CipherTlsEcdhRsaWith3desEdeCbcSha             = CipherSuite(0xc00d)
	CipherTlsEcdhRsaWithAes128CbcSha              = CipherSuite(0xc00e)
	CipherTlsEcdhRsaWithAes256CbcSha              = CipherSuite(0xc00f)
	CipherTlsEcdheRsaWithNullSha                  = CipherSuite(0xc010)
	CipherTlsEcdheRsaWithRc4128Sha                = CipherSuite(0xc011)
	CipherTlsEcdheRsaWith3desEdeCbcSha            = CipherSuite(0xc012)
	CipherTlsEcdheRsaWithAes128CbcSha             = CipherSuite(0xc013)
	CipherTlsEcdheRsaWithAes256CbcSha             = CipherSuite(0xc014)
	CipherTlsEcdhAnonWithNullSha                  = CipherSuite(0xc015)
	CipherTlsEcdhAnonWithRc4128Sha                = CipherSuite(0xc016)
	CipherTlsEcdhAnonWith3desEdeCbcSha            = CipherSuite(0xc017)
	CipherTlsEcdhAnonWithAes128CbcSha             = CipherSuite(0xc018)
	CipherTlsEcdhAnonWithAes256CbcSha             = CipherSuite(0xc019)
	CipherTlsSrpShaWith3desEdeCbcSha              = CipherSuite(0xc01a)
	CipherTlsSrpShaRsaWith3desEdeCbcSha           = CipherSuite(0xc01b)
	CipherTlsSrpShaDssWith3desEdeCbcSha           = CipherSuite(0xc01c)
	CipherTlsSrpShaWithAes128CbcSha               = CipherSuite(0xc01d)
	CipherTlsSrpShaRsaWithAes128CbcSha            = CipherSuite(0xc01e)
	CipherTlsSrpShaDssWithAes128CbcSha            = CipherSuite(0xc01f)
	CipherTlsSrpShaWithAes256CbcSha               = CipherSuite(0xc020)
	CipherTlsSrpShaRsaWithAes256CbcSha            = CipherSuite(0xc021)
	CipherTlsSrpShaDssWithAes256CbcSha            = CipherSuite(0xc022)
	CipherTlsEcdheEcdsaWithAes128CbcSha256        = CipherSuite(0xc023)
	CipherTlsEcdheEcdsaWithAes256CbcSha384        = CipherSuite(0xc024)
	CipherTlsEcdhEcdsaWithAes128CbcSha256         = CipherSuite(0xc025)
	CipherTlsEcdhEcdsaWithAes256CbcSha384         = CipherSuite(0xc026)
	CipherTlsEcdheRsaWithAes128CbcSha256          = CipherSuite(0xc027)
	CipherTlsEcdheRsaWithAes256CbcSha384          = CipherSuite(0xc028)
	CipherTlsEcdhRsaWithAes128CbcSha256           = CipherSuite(0xc029)
	CipherTlsEcdhRsaWithAes256CbcSha384           = CipherSuite(0xc02a)
	CipherTlsEcdheEcdsaWithAes128GcmSha256        = CipherSuite(0xc02b)
	CipherTlsEcdheEcdsaWithAes256GcmSha384        = CipherSuite(0xc02c)
	CipherTlsEcdhEcdsaWithAes128GcmSha256         = CipherSuite(0xc02d)
	CipherTlsEcdhEcdsaWithAes256GcmSha384         = CipherSuite(0xc02e)
	CipherTlsEcdheRsaWithAes128GcmSha256          = CipherSuite(0xc02f)
	CipherTlsEcdheRsaWithAes256GcmSha384          = CipherSuite(0xc030)
	CipherTlsEcdhRsaWithAes128GcmSha256           = CipherSuite(0xc031)
	CipherTlsEcdhRsaWithAes256GcmSha384           = CipherSuite(0xc032)
	CipherTlsEcdhePskWithRc4128Sha                = CipherSuite(0xc033)
	CipherTlsEcdhePskWith3desEdeCbcSha            = CipherSuite(0xc034)
	CipherTlsEcdhePskWithAes128CbcSha             = CipherSuite(0xc035)
	CipherTlsEcdhePskWithAes256CbcSha             = CipherSuite(0xc036)
	CipherTlsEcdhePskWithAes128CbcSha256          = CipherSuite(0xc037)
	CipherTlsEcdhePskWithAes256CbcSha384          = CipherSuite(0xc038)
	CipherTlsEcdhePskWithNullSha                  = CipherSuite(0xc039)
	CipherTlsEcdhePskWithNullSha256               = CipherSuite(0xc03a)
	CipherTlsEcdhePskWithNullSha384               = CipherSuite(0xc03b)
	CipherTlsRsaWithAria128CbcSha256              = CipherSuite(0xc03c)
	CipherTlsRsaWithAria256CbcSha384              = CipherSuite(0xc03d)
	CipherTlsDhDssWithAria128CbcSha256            = CipherSuite(0xc03e)
	CipherTlsDhDssWithAria256CbcSha384            = CipherSuite(0xc03f)
	CipherTlsDhRsaWithAria128CbcSha256            = CipherSuite(0xc040)
	CipherTlsDhRsaWithAria256CbcSha384            = CipherSuite(0xc041)
	CipherTlsDheDssWithAria128CbcSha256           = CipherSuite(0xc042)
	CipherTlsDheDssWithAria256CbcSha384           = CipherSuite(0xc043)
	CipherTlsDheRsaWithAria128CbcSha256           = CipherSuite(0xc044)
	CipherTlsDheRsaWithAria256CbcSha384           = CipherSuite(0xc045)
	CipherTlsDhAnonWithAria128CbcSha256           = CipherSuite(0xc046)
	CipherTlsDhAnonWithAria256CbcSha384           = CipherSuite(0xc047)
	CipherTlsEcdheEcdsaWithAria128CbcSha256       = CipherSuite(0xc048)
	CipherTlsEcdheEcdsaWithAria256CbcSha384       = CipherSuite(0xc049)
	CipherTlsEcdhEcdsaWithAria128CbcSha256        = CipherSuite(0xc04a)
	CipherTlsEcdhEcdsaWithAria256CbcSha384        = CipherSuite(0xc04b)
	CipherTlsEcdheRsaWithAria128CbcSha256         = CipherSuite(0xc04c)
	CipherTlsEcdheRsaWithAria256CbcSha384         = CipherSuite(0xc04d)
	CipherTlsEcdhRsaWithAria128CbcSha256          = CipherSuite(0xc04e)
	CipherTlsEcdhRsaWithAria256CbcSha384          = CipherSuite(0xc04f)
	CipherTlsRsaWithAria128GcmSha256              = CipherSuite(0xc050)
	CipherTlsRsaWithAria256GcmSha384              = CipherSuite(0xc051)
	CipherTlsDheRsaWithAria128GcmSha256           = CipherSuite(0xc052)
	CipherTlsDheRsaWithAria256GcmSha384           = CipherSuite(0xc053)
	CipherTlsDhRsaWithAria128GcmSha256            = CipherSuite(0xc054)
	CipherTlsDhRsaWithAria256GcmSha384            = CipherSuite(0xc055)
	CipherTlsDheDssWithAria128GcmSha256           = CipherSuite(0xc056)
	CipherTlsDheDssWithAria256GcmSha384           = CipherSuite(0xc057)
	CipherTlsDhDssWithAria128GcmSha256            = CipherSuite(0xc058)
	CipherTlsDhDssWithAria256GcmSha384            = CipherSuite(0xc059)
	CipherTlsDhAnonWithAria128GcmSha256           = CipherSuite(0xc05a)
	CipherTlsDhAnonWithAria256GcmSha384           = CipherSuite(0xc05b)
	CipherTlsEcdheEcdsaWithAria128GcmSha256       = CipherSuite(0xc05c)
	CipherTlsEcdheEcdsaWithAria256GcmSha384       = CipherSuite(0xc05d)
	CipherTlsEcdhEcdsaWithAria128GcmSha256        = CipherSuite(0xc05e)
	CipherTlsEcdhEcdsaWithAria256GcmSha384        = CipherSuite(0xc05f)
	CipherTlsEcdheRsaWithAria128GcmSha256         = CipherSuite(0xc060)
	CipherTlsEcdheRsaWithAria256GcmSha384         = CipherSuite(0xc061)
	CipherTlsEcdhRsaWithAria128GcmSha256          = CipherSuite(0xc062)
	CipherTlsEcdhRsaWithAria256GcmSha384          = CipherSuite(0xc063)
	CipherTlsPskWithAria128CbcSha256              = CipherSuite(0xc064)
	CipherTlsPskWithAria256CbcSha384              = CipherSuite(0xc065)
	CipherTlsDhePskWithAria128CbcSha256           = CipherSuite(0xc066)
	CipherTlsDhePskWithAria256CbcSha384           = CipherSuite(0xc067)
	CipherTlsRsaPskWithAria128CbcSha256           = CipherSuite(0xc068)
	CipherTlsRsaPskWithAria256CbcSha384           = CipherSuite(0xc069)
	CipherTlsPskWithAria128GcmSha256              = CipherSuite(0xc06a)
	CipherTlsPskWithAria256GcmSha384              = CipherSuite(0xc06b)
	CipherTlsDhePskWithAria128GcmSha256           = CipherSuite(0xc06c)
	CipherTlsDhePskWithAria256GcmSha384           = CipherSuite(0xc06d)
	CipherTlsRsaPskWithAria128GcmSha256           = CipherSuite(0xc06e)
	CipherTlsRsaPskWithAria256GcmSha384           = CipherSuite(0xc06f)
	CipherTlsEcdhePskWithAria128CbcSha256         = CipherSuite(0xc070)
	CipherTlsEcdhePskWithAria256CbcSha384         = CipherSuite(0xc071)
	CipherTlsEcdheEcdsaWithCamellia128CbcSha256   = CipherSuite(0xc072)
	CipherTlsEcdheEcdsaWithCamellia256CbcSha384   = CipherSuite(0xc073)
	CipherTlsEcdhEcdsaWithCamellia128CbcSha256    = CipherSuite(0xc074)
	CipherTlsEcdhEcdsaWithCamellia256CbcSha384    = CipherSuite(0xc075)
	CipherTlsEcdheRsaWithCamellia128CbcSha256     = CipherSuite(0xc076)
	CipherTlsEcdheRsaWithCamellia256CbcSha384     = CipherSuite(0xc077)
	CipherTlsEcdhRsaWithCamellia128CbcSha256      = CipherSuite(0xc078)
	CipherTlsEcdhRsaWithCamellia256CbcSha384      = CipherSuite(0xc079)
	CipherTlsRsaWithCamellia128GcmSha256          = CipherSuite(0xc07a)
	CipherTlsRsaWithCamellia256GcmSha384          = CipherSuite(0xc07b)
	CipherTlsDheRsaWithCamellia128GcmSha256       = CipherSuite(0xc07c)
	CipherTlsDheRsaWithCamellia256GcmSha384       = CipherSuite(0xc07d)
	CipherTlsDhRsaWithCamellia128GcmSha256        = CipherSuite(0xc07e)
	CipherTlsDhRsaWithCamellia256GcmSha384        = CipherSuite(0xc07f)
	CipherTlsDheDssWithCamellia128GcmSha256       = CipherSuite(0xc080)
	CipherTlsDheDssWithCamellia256GcmSha384       = CipherSuite(0xc081)
	CipherTlsDhDssWithCamellia128GcmSha256        = CipherSuite(0xc082)
	CipherTlsDhDssWithCamellia256GcmSha384        = CipherSuite(0xc083)
	CipherTlsDhAnonWithCamellia128GcmSha256       = CipherSuite(0xc084)
	CipherTlsDhAnonWithCamellia256GcmSha384       = CipherSuite(0xc085)
	CipherTlsEcdheEcdsaWithCamellia128GcmSha256   = CipherSuite(0xc086)
	CipherTlsEcdheEcdsaWithCamellia256GcmSha384   = CipherSuite(0xc087)
	CipherTlsEcdhEcdsaWithCamellia128GcmSha256    = CipherSuite(0xc088)
	CipherTlsEcdhEcdsaWithCamellia256GcmSha384    = CipherSuite(0xc089)
	CipherTlsEcdheRsaWithCamellia128GcmSha256     = CipherSuite(0xc08a)
	CipherTlsEcdheRsaWithCamellia256GcmSha384     = CipherSuite(0xc08b)
	CipherTlsEcdhRsaWithCamellia128GcmSha256      = CipherSuite(0xc08c)
	CipherTlsEcdhRsaWithCamellia256GcmSha384      = CipherSuite(0xc08d)
	CipherTlsPskWithCamellia128GcmSha256          = CipherSuite(0xc08e)
	CipherTlsPskWithCamellia256GcmSha384          = CipherSuite(0xc08f)
	CipherTlsDhePskWithCamellia128GcmSha256       = CipherSuite(0xc090)
	CipherTlsDhePskWithCamellia256GcmSha384       = CipherSuite(0xc091)
	CipherTlsRsaPskWithCamellia128GcmSha256       = CipherSuite(0xc092)
	CipherTlsRsaPskWithCamellia256GcmSha384       = CipherSuite(0xc093)
	CipherTlsPskWithCamellia128CbcSha256          = CipherSuite(0xc094)
	CipherTlsPskWithCamellia256CbcSha384          = CipherSuite(0xc095)
	CipherTlsDhePskWithCamellia128CbcSha256       = CipherSuite(0xc096)
	CipherTlsDhePskWithCamellia256CbcSha384       = CipherSuite(0xc097)
	CipherTlsRsaPskWithCamellia128CbcSha256       = CipherSuite(0xc098)
	CipherTlsRsaPskWithCamellia256CbcSha384       = CipherSuite(0xc099)
	CipherTlsEcdhePskWithCamellia128CbcSha256     = CipherSuite(0xc09a)
	CipherTlsEcdhePskWithCamellia256CbcSha384     = CipherSuite(0xc09b)
	CipherTlsRsaWithAes128Ccm                     = CipherSuite(0xc09c)
	CipherTlsRsaWithAes256Ccm                     = CipherSuite(0xc09d)
	CipherTlsDheRsaWithAes128Ccm                  = CipherSuite(0xc09e)
	CipherTlsDheRsaWithAes256Ccm                  = CipherSuite(0xc09f)
	CipherTlsRsaWithAes128Ccm8                    = CipherSuite(0xc0a0)
	CipherTlsRsaWithAes256Ccm8                    = CipherSuite(0xc0a1)
	CipherTlsDheRsaWithAes128Ccm8                 = CipherSuite(0xc0a2)
	CipherTlsDheRsaWithAes256Ccm8                 = CipherSuite(0xc0a3)
	CipherTlsPskWithAes128Ccm                     = CipherSuite(0xc0a4)
	CipherTlsPskWithAes256Ccm                     = CipherSuite(0xc0a5)
	CipherTlsDhePskWithAes128Ccm                  = CipherSuite(0xc0a6)
	CipherTlsDhePskWithAes256Ccm                  = CipherSuite(0xc0a7)
	CipherTlsPskWithAes128Ccm8                    = CipherSuite(0xc0a8)
	CipherTlsPskWithAes256Ccm8                    = CipherSuite(0xc0a9)
	CipherTlsPskDheWithAes128Ccm8                 = CipherSuite(0xc0aa)
	CipherTlsPskDheWithAes256Ccm8                 = CipherSuite(0xc0ab)
	CipherTlsEcdheEcdsaWithAes128Ccm              = CipherSuite(0xc0ac)
	CipherTlsEcdheEcdsaWithAes256Ccm              = CipherSuite(0xc0ad)
	CipherTlsEcdheEcdsaWithAes128Ccm8             = CipherSuite(0xc0ae)
	CipherTlsEcdheEcdsaWithAes256Ccm8             = CipherSuite(0xc0af)
	CipherTlsEccpwdWithAes128GcmSha256            = CipherSuite(0xc0b0)
	CipherTlsEccpwdWithAes256GcmSha384            = CipherSuite(0xc0b1)
	CipherTlsEccpwdWithAes128CcmSha256            = CipherSuite(0xc0b2)
	CipherTlsEccpwdWithAes256CcmSha384            = CipherSuite(0xc0b3)
	CipherTlsSha256Sha256                         = CipherSuite(0xc0b4)
	CipherTlsSha384Sha384                         = CipherSuite(0xc0b5)
	CipherTlsGostr341112256WithKuznyechikCtrOmac  = CipherSuite(0xc100)
	CipherTlsGostr341112256WithMagmaCtrOmac       = CipherSuite(0xc101)
	CipherTlsGostr341112256With28147CntImit       = CipherSuite(0xc102)
	CipherTlsGostr341112256WithKuznyechikMgmL     = CipherSuite(0xc103)
	CipherTlsGostr341112256WithMagmaMgmL          = CipherSuite(0xc104)
	CipherTlsGostr341112256WithKuznyechikMgmS     = CipherSuite(0xc105)
	CipherTlsGostr341112256WithMagmaMgmS          = CipherSuite(0xc106)
	CipherTlsEcdheRsaWithChacha20Poly1305Sha256   = CipherSuite(0xcca8)
	CipherTlsEcdheEcdsaWithChacha20Poly1305Sha256 = CipherSuite(0xcca9)
	CipherTlsDheRsaWithChacha20Poly1305Sha256     = CipherSuite(0xccaa)
	CipherTlsPskWithChacha20Poly1305Sha256        = CipherSuite(0xccab)
	CipherTlsEcdhePskWithChacha20Poly1305Sha256   = CipherSuite(0xccac)
	CipherTlsDhePskWithChacha20Poly1305Sha256     = CipherSuite(0xccad)
	CipherTlsRsaPskWithChacha20Poly1305Sha256     = CipherSuite(0xccae)
	CipherTlsEcdhePskWithAes128GcmSha256          = CipherSuite(0xd001)
	CipherTlsEcdhePskWithAes256GcmSha384          = CipherSuite(0xd002)
	CipherTlsEcdhePskWithAes128Ccm8Sha256         = CipherSuite(0xd003)
	CipherTlsEcdhePskWithAes128CcmSha256          = CipherSuite(0xd005)
)

func (cipher *CipherSuite) String() string {
	switch *cipher {
	case CipherTlsNullWithNullNull:
		return "NULL-WITH-NULL-NULL"
	case CipherTlsRsaWithNullMd5:
		return "RSA-WITH-NULL-MD5"
	case CipherTlsRsaWithNullSha:
		return "RSA-WITH-NULL-SHA"
	case CipherTlsRsaExportWithRc440Md5:
		return "RSA-EXPORT-WITH-RC4-40-MD5"
	case CipherTlsRsaWithRc4128Md5:
		return "RSA-WITH-RC4-128-MD5"
	case CipherTlsRsaWithRc4128Sha:
		return "RSA-WITH-RC4-128-SHA"
	case CipherTlsRsaExportWithRc2Cbc40Md5:
		return "RSA-EXPORT-WITH-RC2-CBC-40-MD5"
	case CipherTlsRsaWithIdeaCbcSha:
		return "RSA-WITH-IDEA-CBC-SHA"
	case CipherTlsRsaExportWithDes40CbcSha:
		return "RSA-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsRsaWithDesCbcSha:
		return "RSA-WITH-DES-CBC-SHA"
	case CipherTlsRsaWith3desEdeCbcSha:
		return "RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDhDssExportWithDes40CbcSha:
		return "DH-DSS-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsDhDssWithDesCbcSha:
		return "DH-DSS-WITH-DES-CBC-SHA"
	case CipherTlsDhDssWith3desEdeCbcSha:
		return "DH-DSS-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDhRsaExportWithDes40CbcSha:
		return "DH-RSA-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsDhRsaWithDesCbcSha:
		return "DH-RSA-WITH-DES-CBC-SHA"
	case CipherTlsDhRsaWith3desEdeCbcSha:
		return "DH-RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDheDssExportWithDes40CbcSha:
		return "DHE-DSS-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsDheDssWithDesCbcSha:
		return "DHE-DSS-WITH-DES-CBC-SHA"
	case CipherTlsDheDssWith3desEdeCbcSha:
		return "DHE-DSS-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDheRsaExportWithDes40CbcSha:
		return "DHE-RSA-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsDheRsaWithDesCbcSha:
		return "DHE-RSA-WITH-DES-CBC-SHA"
	case CipherTlsDheRsaWith3desEdeCbcSha:
		return "DHE-RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDhAnonExportWithRc440Md5:
		return "DH-ANON-EXPORT-WITH-RC4-40-MD5"
	case CipherTlsDhAnonWithRc4128Md5:
		return "DH-ANON-WITH-RC4-128-MD5"
	case CipherTlsDhAnonExportWithDes40CbcSha:
		return "DH-ANON-EXPORT-WITH-DES40-CBC-SHA"
	case CipherTlsDhAnonWithDesCbcSha:
		return "DH-ANON-WITH-DES-CBC-SHA"
	case CipherTlsDhAnonWith3desEdeCbcSha:
		return "DH-ANON-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsKrb5WithDesCbcSha:
		return "KRB5-WITH-DES-CBC-SHA"
	case CipherTlsKrb5With3desEdeCbcSha:
		return "KRB5-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsKrb5WithRc4128Sha:
		return "KRB5-WITH-RC4-128-SHA"
	case CipherTlsKrb5WithIdeaCbcSha:
		return "KRB5-WITH-IDEA-CBC-SHA"
	case CipherTlsKrb5WithDesCbcMd5:
		return "KRB5-WITH-DES-CBC-MD5"
	case CipherTlsKrb5With3desEdeCbcMd5:
		return "KRB5-WITH-3DES-EDE-CBC-MD5"
	case CipherTlsKrb5WithRc4128Md5:
		return "KRB5-WITH-RC4-128-MD5"
	case CipherTlsKrb5WithIdeaCbcMd5:
		return "KRB5-WITH-IDEA-CBC-MD5"
	case CipherTlsKrb5ExportWithDesCbc40Sha:
		return "KRB5-EXPORT-WITH-DES-CBC-40-SHA"
	case CipherTlsKrb5ExportWithRc2Cbc40Sha:
		return "KRB5-EXPORT-WITH-RC2-CBC-40-SHA"
	case CipherTlsKrb5ExportWithRc440Sha:
		return "KRB5-EXPORT-WITH-RC4-40-SHA"
	case CipherTlsKrb5ExportWithDesCbc40Md5:
		return "KRB5-EXPORT-WITH-DES-CBC-40-MD5"
	case CipherTlsKrb5ExportWithRc2Cbc40Md5:
		return "KRB5-EXPORT-WITH-RC2-CBC-40-MD5"
	case CipherTlsKrb5ExportWithRc440Md5:
		return "KRB5-EXPORT-WITH-RC4-40-MD5"
	case CipherTlsPskWithNullSha:
		return "PSK-WITH-NULL-SHA"
	case CipherTlsDhePskWithNullSha:
		return "DHE-PSK-WITH-NULL-SHA"
	case CipherTlsRsaPskWithNullSha:
		return "RSA-PSK-WITH-NULL-SHA"
	case CipherTlsRsaWithAes128CbcSha:
		return "RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsDhDssWithAes128CbcSha:
		return "DH-DSS-WITH-AES-128-CBC-SHA"
	case CipherTlsDhRsaWithAes128CbcSha:
		return "DH-RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsDheDssWithAes128CbcSha:
		return "DHE-DSS-WITH-AES-128-CBC-SHA"
	case CipherTlsDheRsaWithAes128CbcSha:
		return "DHE-RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsDhAnonWithAes128CbcSha:
		return "DH-ANON-WITH-AES-128-CBC-SHA"
	case CipherTlsRsaWithAes256CbcSha:
		return "RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsDhDssWithAes256CbcSha:
		return "DH-DSS-WITH-AES-256-CBC-SHA"
	case CipherTlsDhRsaWithAes256CbcSha:
		return "DH-RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsDheDssWithAes256CbcSha:
		return "DHE-DSS-WITH-AES-256-CBC-SHA"
	case CipherTlsDheRsaWithAes256CbcSha:
		return "DHE-RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsDhAnonWithAes256CbcSha:
		return "DH-ANON-WITH-AES-256-CBC-SHA"
	case CipherTlsRsaWithNullSha256:
		return "RSA-WITH-NULL-SHA256"
	case CipherTlsRsaWithAes128CbcSha256:
		return "RSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsRsaWithAes256CbcSha256:
		return "RSA-WITH-AES-256-CBC-SHA256"
	case CipherTlsDhDssWithAes128CbcSha256:
		return "DH-DSS-WITH-AES-128-CBC-SHA256"
	case CipherTlsDhRsaWithAes128CbcSha256:
		return "DH-RSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsDheDssWithAes128CbcSha256:
		return "DHE-DSS-WITH-AES-128-CBC-SHA256"
	case CipherTlsRsaWithCamellia128CbcSha:
		return "RSA-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDhDssWithCamellia128CbcSha:
		return "DH-DSS-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDhRsaWithCamellia128CbcSha:
		return "DH-RSA-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDheDssWithCamellia128CbcSha:
		return "DHE-DSS-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDheRsaWithCamellia128CbcSha:
		return "DHE-RSA-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDhAnonWithCamellia128CbcSha:
		return "DH-ANON-WITH-CAMELLIA-128-CBC-SHA"
	case CipherTlsDheRsaWithAes128CbcSha256:
		return "DHE-RSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsDhDssWithAes256CbcSha256:
		return "DH-DSS-WITH-AES-256-CBC-SHA256"
	case CipherTlsDhRsaWithAes256CbcSha256:
		return "DH-RSA-WITH-AES-256-CBC-SHA256"
	case CipherTlsDheDssWithAes256CbcSha256:
		return "DHE-DSS-WITH-AES-256-CBC-SHA256"
	case CipherTlsDheRsaWithAes256CbcSha256:
		return "DHE-RSA-WITH-AES-256-CBC-SHA256"
	case CipherTlsDhAnonWithAes128CbcSha256:
		return "DH-ANON-WITH-AES-128-CBC-SHA256"
	case CipherTlsDhAnonWithAes256CbcSha256:
		return "DH-ANON-WITH-AES-256-CBC-SHA256"
	case CipherTlsRsaWithCamellia256CbcSha:
		return "RSA-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsDhDssWithCamellia256CbcSha:
		return "DH-DSS-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsDhRsaWithCamellia256CbcSha:
		return "DH-RSA-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsDheDssWithCamellia256CbcSha:
		return "DHE-DSS-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsDheRsaWithCamellia256CbcSha:
		return "DHE-RSA-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsDhAnonWithCamellia256CbcSha:
		return "DH-ANON-WITH-CAMELLIA-256-CBC-SHA"
	case CipherTlsPskWithRc4128Sha:
		return "PSK-WITH-RC4-128-SHA"
	case CipherTlsPskWith3desEdeCbcSha:
		return "PSK-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsPskWithAes128CbcSha:
		return "PSK-WITH-AES-128-CBC-SHA"
	case CipherTlsPskWithAes256CbcSha:
		return "PSK-WITH-AES-256-CBC-SHA"
	case CipherTlsDhePskWithRc4128Sha:
		return "DHE-PSK-WITH-RC4-128-SHA"
	case CipherTlsDhePskWith3desEdeCbcSha:
		return "DHE-PSK-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsDhePskWithAes128CbcSha:
		return "DHE-PSK-WITH-AES-128-CBC-SHA"
	case CipherTlsDhePskWithAes256CbcSha:
		return "DHE-PSK-WITH-AES-256-CBC-SHA"
	case CipherTlsRsaPskWithRc4128Sha:
		return "RSA-PSK-WITH-RC4-128-SHA"
	case CipherTlsRsaPskWith3desEdeCbcSha:
		return "RSA-PSK-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsRsaPskWithAes128CbcSha:
		return "RSA-PSK-WITH-AES-128-CBC-SHA"
	case CipherTlsRsaPskWithAes256CbcSha:
		return "RSA-PSK-WITH-AES-256-CBC-SHA"
	case CipherTlsRsaWithSeedCbcSha:
		return "RSA-WITH-SEED-CBC-SHA"
	case CipherTlsDhDssWithSeedCbcSha:
		return "DH-DSS-WITH-SEED-CBC-SHA"
	case CipherTlsDhRsaWithSeedCbcSha:
		return "DH-RSA-WITH-SEED-CBC-SHA"
	case CipherTlsDheDssWithSeedCbcSha:
		return "DHE-DSS-WITH-SEED-CBC-SHA"
	case CipherTlsDheRsaWithSeedCbcSha:
		return "DHE-RSA-WITH-SEED-CBC-SHA"
	case CipherTlsDhAnonWithSeedCbcSha:
		return "DH-ANON-WITH-SEED-CBC-SHA"
	case CipherTlsRsaWithAes128GcmSha256:
		return "RSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsRsaWithAes256GcmSha384:
		return "RSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsDheRsaWithAes128GcmSha256:
		return "DHE-RSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsDheRsaWithAes256GcmSha384:
		return "DHE-RSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsDhRsaWithAes128GcmSha256:
		return "DH-RSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsDhRsaWithAes256GcmSha384:
		return "DH-RSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsDheDssWithAes128GcmSha256:
		return "DHE-DSS-WITH-AES-128-GCM-SHA256"
	case CipherTlsDheDssWithAes256GcmSha384:
		return "DHE-DSS-WITH-AES-256-GCM-SHA384"
	case CipherTlsDhDssWithAes128GcmSha256:
		return "DH-DSS-WITH-AES-128-GCM-SHA256"
	case CipherTlsDhDssWithAes256GcmSha384:
		return "DH-DSS-WITH-AES-256-GCM-SHA384"
	case CipherTlsDhAnonWithAes128GcmSha256:
		return "DH-ANON-WITH-AES-128-GCM-SHA256"
	case CipherTlsDhAnonWithAes256GcmSha384:
		return "DH-ANON-WITH-AES-256-GCM-SHA384"
	case CipherTlsPskWithAes128GcmSha256:
		return "PSK-WITH-AES-128-GCM-SHA256"
	case CipherTlsPskWithAes256GcmSha384:
		return "PSK-WITH-AES-256-GCM-SHA384"
	case CipherTlsDhePskWithAes128GcmSha256:
		return "DHE-PSK-WITH-AES-128-GCM-SHA256"
	case CipherTlsDhePskWithAes256GcmSha384:
		return "DHE-PSK-WITH-AES-256-GCM-SHA384"
	case CipherTlsRsaPskWithAes128GcmSha256:
		return "RSA-PSK-WITH-AES-128-GCM-SHA256"
	case CipherTlsRsaPskWithAes256GcmSha384:
		return "RSA-PSK-WITH-AES-256-GCM-SHA384"
	case CipherTlsPskWithAes128CbcSha256:
		return "PSK-WITH-AES-128-CBC-SHA256"
	case CipherTlsPskWithAes256CbcSha384:
		return "PSK-WITH-AES-256-CBC-SHA384"
	case CipherTlsPskWithNullSha256:
		return "PSK-WITH-NULL-SHA256"
	case CipherTlsPskWithNullSha384:
		return "PSK-WITH-NULL-SHA384"
	case CipherTlsDhePskWithAes128CbcSha256:
		return "DHE-PSK-WITH-AES-128-CBC-SHA256"
	case CipherTlsDhePskWithAes256CbcSha384:
		return "DHE-PSK-WITH-AES-256-CBC-SHA384"
	case CipherTlsDhePskWithNullSha256:
		return "DHE-PSK-WITH-NULL-SHA256"
	case CipherTlsDhePskWithNullSha384:
		return "DHE-PSK-WITH-NULL-SHA384"
	case CipherTlsRsaPskWithAes128CbcSha256:
		return "RSA-PSK-WITH-AES-128-CBC-SHA256"
	case CipherTlsRsaPskWithAes256CbcSha384:
		return "RSA-PSK-WITH-AES-256-CBC-SHA384"
	case CipherTlsRsaPskWithNullSha256:
		return "RSA-PSK-WITH-NULL-SHA256"
	case CipherTlsRsaPskWithNullSha384:
		return "RSA-PSK-WITH-NULL-SHA384"
	case CipherTlsRsaWithCamellia128CbcSha256:
		return "RSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDhDssWithCamellia128CbcSha256:
		return "DH-DSS-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDhRsaWithCamellia128CbcSha256:
		return "DH-RSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDheDssWithCamellia128CbcSha256:
		return "DHE-DSS-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDheRsaWithCamellia128CbcSha256:
		return "DHE-RSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDhAnonWithCamellia128CbcSha256:
		return "DH-ANON-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsRsaWithCamellia256CbcSha256:
		return "RSA-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsDhDssWithCamellia256CbcSha256:
		return "DH-DSS-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsDhRsaWithCamellia256CbcSha256:
		return "DH-RSA-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsDheDssWithCamellia256CbcSha256:
		return "DHE-DSS-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsDheRsaWithCamellia256CbcSha256:
		return "DHE-RSA-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsDhAnonWithCamellia256CbcSha256:
		return "DH-ANON-WITH-CAMELLIA-256-CBC-SHA256"
	case CipherTlsSm4GcmSm3:
		return "SM4-GCM-SM3"
	case CipherTlsSm4CcmSm3:
		return "SM4-CCM-SM3"
	case CipherTlsEmptyRenegotiationInfoScsv:
		return "EMPTY-RENEGOTIATION-INFO-SCSV"
	case CipherTlsAes128GcmSha256:
		return "AES-128-GCM-SHA256"
	case CipherTlsAes256GcmSha384:
		return "AES-256-GCM-SHA384"
	case CipherTlsChacha20Poly1305Sha256:
		return "CHACHA20-POLY1305-SHA256"
	case CipherTlsAes128CcmSha256:
		return "AES-128-CCM-SHA256"
	case CipherTlsAes128Ccm8Sha256:
		return "AES-128-CCM-8-SHA256"
	case CipherTlsAegis256Sha512:
		return "AEGIS-256-SHA512"
	case CipherTlsAegis128lSha256:
		return "AEGIS-128L-SHA256"
	case CipherTlsFallbackScsv:
		return "FALLBACK-SCSV"
	case CipherTlsEcdhEcdsaWithNullSha:
		return "ECDH-ECDSA-WITH-NULL-SHA"
	case CipherTlsEcdhEcdsaWithRc4128Sha:
		return "ECDH-ECDSA-WITH-RC4-128-SHA"
	case CipherTlsEcdhEcdsaWith3desEdeCbcSha:
		return "ECDH-ECDSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdhEcdsaWithAes128CbcSha:
		return "ECDH-ECDSA-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdhEcdsaWithAes256CbcSha:
		return "ECDH-ECDSA-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdheEcdsaWithNullSha:
		return "ECDHE-ECDSA-WITH-NULL-SHA"
	case CipherTlsEcdheEcdsaWithRc4128Sha:
		return "ECDHE-ECDSA-WITH-RC4-128-SHA"
	case CipherTlsEcdheEcdsaWith3desEdeCbcSha:
		return "ECDHE-ECDSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdheEcdsaWithAes128CbcSha:
		return "ECDHE-ECDSA-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdheEcdsaWithAes256CbcSha:
		return "ECDHE-ECDSA-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdhRsaWithNullSha:
		return "ECDH-RSA-WITH-NULL-SHA"
	case CipherTlsEcdhRsaWithRc4128Sha:
		return "ECDH-RSA-WITH-RC4-128-SHA"
	case CipherTlsEcdhRsaWith3desEdeCbcSha:
		return "ECDH-RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdhRsaWithAes128CbcSha:
		return "ECDH-RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdhRsaWithAes256CbcSha:
		return "ECDH-RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdheRsaWithNullSha:
		return "ECDHE-RSA-WITH-NULL-SHA"
	case CipherTlsEcdheRsaWithRc4128Sha:
		return "ECDHE-RSA-WITH-RC4-128-SHA"
	case CipherTlsEcdheRsaWith3desEdeCbcSha:
		return "ECDHE-RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdheRsaWithAes128CbcSha:
		return "ECDHE-RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdheRsaWithAes256CbcSha:
		return "ECDHE-RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdhAnonWithNullSha:
		return "ECDH-ANON-WITH-NULL-SHA"
	case CipherTlsEcdhAnonWithRc4128Sha:
		return "ECDH-ANON-WITH-RC4-128-SHA"
	case CipherTlsEcdhAnonWith3desEdeCbcSha:
		return "ECDH-ANON-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdhAnonWithAes128CbcSha:
		return "ECDH-ANON-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdhAnonWithAes256CbcSha:
		return "ECDH-ANON-WITH-AES-256-CBC-SHA"
	case CipherTlsSrpShaWith3desEdeCbcSha:
		return "SRP-SHA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsSrpShaRsaWith3desEdeCbcSha:
		return "SRP-SHA-RSA-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsSrpShaDssWith3desEdeCbcSha:
		return "SRP-SHA-DSS-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsSrpShaWithAes128CbcSha:
		return "SRP-SHA-WITH-AES-128-CBC-SHA"
	case CipherTlsSrpShaRsaWithAes128CbcSha:
		return "SRP-SHA-RSA-WITH-AES-128-CBC-SHA"
	case CipherTlsSrpShaDssWithAes128CbcSha:
		return "SRP-SHA-DSS-WITH-AES-128-CBC-SHA"
	case CipherTlsSrpShaWithAes256CbcSha:
		return "SRP-SHA-WITH-AES-256-CBC-SHA"
	case CipherTlsSrpShaRsaWithAes256CbcSha:
		return "SRP-SHA-RSA-WITH-AES-256-CBC-SHA"
	case CipherTlsSrpShaDssWithAes256CbcSha:
		return "SRP-SHA-DSS-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdheEcdsaWithAes128CbcSha256:
		return "ECDHE-ECDSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsEcdheEcdsaWithAes256CbcSha384:
		return "ECDHE-ECDSA-WITH-AES-256-CBC-SHA384"
	case CipherTlsEcdhEcdsaWithAes128CbcSha256:
		return "ECDH-ECDSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsEcdhEcdsaWithAes256CbcSha384:
		return "ECDH-ECDSA-WITH-AES-256-CBC-SHA384"
	case CipherTlsEcdheRsaWithAes128CbcSha256:
		return "ECDHE-RSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsEcdheRsaWithAes256CbcSha384:
		return "ECDHE-RSA-WITH-AES-256-CBC-SHA384"
	case CipherTlsEcdhRsaWithAes128CbcSha256:
		return "ECDH-RSA-WITH-AES-128-CBC-SHA256"
	case CipherTlsEcdhRsaWithAes256CbcSha384:
		return "ECDH-RSA-WITH-AES-256-CBC-SHA384"
	case CipherTlsEcdheEcdsaWithAes128GcmSha256:
		return "ECDHE-ECDSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsEcdheEcdsaWithAes256GcmSha384:
		return "ECDHE-ECDSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsEcdhEcdsaWithAes128GcmSha256:
		return "ECDH-ECDSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsEcdhEcdsaWithAes256GcmSha384:
		return "ECDH-ECDSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsEcdheRsaWithAes128GcmSha256:
		return "ECDHE-RSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsEcdheRsaWithAes256GcmSha384:
		return "ECDHE-RSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsEcdhRsaWithAes128GcmSha256:
		return "ECDH-RSA-WITH-AES-128-GCM-SHA256"
	case CipherTlsEcdhRsaWithAes256GcmSha384:
		return "ECDH-RSA-WITH-AES-256-GCM-SHA384"
	case CipherTlsEcdhePskWithRc4128Sha:
		return "ECDHE-PSK-WITH-RC4-128-SHA"
	case CipherTlsEcdhePskWith3desEdeCbcSha:
		return "ECDHE-PSK-WITH-3DES-EDE-CBC-SHA"
	case CipherTlsEcdhePskWithAes128CbcSha:
		return "ECDHE-PSK-WITH-AES-128-CBC-SHA"
	case CipherTlsEcdhePskWithAes256CbcSha:
		return "ECDHE-PSK-WITH-AES-256-CBC-SHA"
	case CipherTlsEcdhePskWithAes128CbcSha256:
		return "ECDHE-PSK-WITH-AES-128-CBC-SHA256"
	case CipherTlsEcdhePskWithAes256CbcSha384:
		return "ECDHE-PSK-WITH-AES-256-CBC-SHA384"
	case CipherTlsEcdhePskWithNullSha:
		return "ECDHE-PSK-WITH-NULL-SHA"
	case CipherTlsEcdhePskWithNullSha256:
		return "ECDHE-PSK-WITH-NULL-SHA256"
	case CipherTlsEcdhePskWithNullSha384:
		return "ECDHE-PSK-WITH-NULL-SHA384"
	case CipherTlsRsaWithAria128CbcSha256:
		return "RSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsRsaWithAria256CbcSha384:
		return "RSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDhDssWithAria128CbcSha256:
		return "DH-DSS-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDhDssWithAria256CbcSha384:
		return "DH-DSS-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDhRsaWithAria128CbcSha256:
		return "DH-RSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDhRsaWithAria256CbcSha384:
		return "DH-RSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDheDssWithAria128CbcSha256:
		return "DHE-DSS-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDheDssWithAria256CbcSha384:
		return "DHE-DSS-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDheRsaWithAria128CbcSha256:
		return "DHE-RSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDheRsaWithAria256CbcSha384:
		return "DHE-RSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDhAnonWithAria128CbcSha256:
		return "DH-ANON-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDhAnonWithAria256CbcSha384:
		return "DH-ANON-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsEcdheEcdsaWithAria128CbcSha256:
		return "ECDHE-ECDSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsEcdheEcdsaWithAria256CbcSha384:
		return "ECDHE-ECDSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsEcdhEcdsaWithAria128CbcSha256:
		return "ECDH-ECDSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsEcdhEcdsaWithAria256CbcSha384:
		return "ECDH-ECDSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsEcdheRsaWithAria128CbcSha256:
		return "ECDHE-RSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsEcdheRsaWithAria256CbcSha384:
		return "ECDHE-RSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsEcdhRsaWithAria128CbcSha256:
		return "ECDH-RSA-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsEcdhRsaWithAria256CbcSha384:
		return "ECDH-RSA-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsRsaWithAria128GcmSha256:
		return "RSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsRsaWithAria256GcmSha384:
		return "RSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDheRsaWithAria128GcmSha256:
		return "DHE-RSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDheRsaWithAria256GcmSha384:
		return "DHE-RSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDhRsaWithAria128GcmSha256:
		return "DH-RSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDhRsaWithAria256GcmSha384:
		return "DH-RSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDheDssWithAria128GcmSha256:
		return "DHE-DSS-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDheDssWithAria256GcmSha384:
		return "DHE-DSS-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDhDssWithAria128GcmSha256:
		return "DH-DSS-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDhDssWithAria256GcmSha384:
		return "DH-DSS-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDhAnonWithAria128GcmSha256:
		return "DH-ANON-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDhAnonWithAria256GcmSha384:
		return "DH-ANON-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsEcdheEcdsaWithAria128GcmSha256:
		return "ECDHE-ECDSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsEcdheEcdsaWithAria256GcmSha384:
		return "ECDHE-ECDSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsEcdhEcdsaWithAria128GcmSha256:
		return "ECDH-ECDSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsEcdhEcdsaWithAria256GcmSha384:
		return "ECDH-ECDSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsEcdheRsaWithAria128GcmSha256:
		return "ECDHE-RSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsEcdheRsaWithAria256GcmSha384:
		return "ECDHE-RSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsEcdhRsaWithAria128GcmSha256:
		return "ECDH-RSA-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsEcdhRsaWithAria256GcmSha384:
		return "ECDH-RSA-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsPskWithAria128CbcSha256:
		return "PSK-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsPskWithAria256CbcSha384:
		return "PSK-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsDhePskWithAria128CbcSha256:
		return "DHE-PSK-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsDhePskWithAria256CbcSha384:
		return "DHE-PSK-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsRsaPskWithAria128CbcSha256:
		return "RSA-PSK-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsRsaPskWithAria256CbcSha384:
		return "RSA-PSK-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsPskWithAria128GcmSha256:
		return "PSK-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsPskWithAria256GcmSha384:
		return "PSK-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsDhePskWithAria128GcmSha256:
		return "DHE-PSK-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsDhePskWithAria256GcmSha384:
		return "DHE-PSK-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsRsaPskWithAria128GcmSha256:
		return "RSA-PSK-WITH-ARIA-128-GCM-SHA256"
	case CipherTlsRsaPskWithAria256GcmSha384:
		return "RSA-PSK-WITH-ARIA-256-GCM-SHA384"
	case CipherTlsEcdhePskWithAria128CbcSha256:
		return "ECDHE-PSK-WITH-ARIA-128-CBC-SHA256"
	case CipherTlsEcdhePskWithAria256CbcSha384:
		return "ECDHE-PSK-WITH-ARIA-256-CBC-SHA384"
	case CipherTlsEcdheEcdsaWithCamellia128CbcSha256:
		return "ECDHE-ECDSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsEcdheEcdsaWithCamellia256CbcSha384:
		return "ECDHE-ECDSA-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsEcdhEcdsaWithCamellia128CbcSha256:
		return "ECDH-ECDSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsEcdhEcdsaWithCamellia256CbcSha384:
		return "ECDH-ECDSA-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsEcdheRsaWithCamellia128CbcSha256:
		return "ECDHE-RSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsEcdheRsaWithCamellia256CbcSha384:
		return "ECDHE-RSA-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsEcdhRsaWithCamellia128CbcSha256:
		return "ECDH-RSA-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsEcdhRsaWithCamellia256CbcSha384:
		return "ECDH-RSA-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsRsaWithCamellia128GcmSha256:
		return "RSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsRsaWithCamellia256GcmSha384:
		return "RSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDheRsaWithCamellia128GcmSha256:
		return "DHE-RSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDheRsaWithCamellia256GcmSha384:
		return "DHE-RSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDhRsaWithCamellia128GcmSha256:
		return "DH-RSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDhRsaWithCamellia256GcmSha384:
		return "DH-RSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDheDssWithCamellia128GcmSha256:
		return "DHE-DSS-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDheDssWithCamellia256GcmSha384:
		return "DHE-DSS-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDhDssWithCamellia128GcmSha256:
		return "DH-DSS-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDhDssWithCamellia256GcmSha384:
		return "DH-DSS-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDhAnonWithCamellia128GcmSha256:
		return "DH-ANON-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDhAnonWithCamellia256GcmSha384:
		return "DH-ANON-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsEcdheEcdsaWithCamellia128GcmSha256:
		return "ECDHE-ECDSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsEcdheEcdsaWithCamellia256GcmSha384:
		return "ECDHE-ECDSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsEcdhEcdsaWithCamellia128GcmSha256:
		return "ECDH-ECDSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsEcdhEcdsaWithCamellia256GcmSha384:
		return "ECDH-ECDSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsEcdheRsaWithCamellia128GcmSha256:
		return "ECDHE-RSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsEcdheRsaWithCamellia256GcmSha384:
		return "ECDHE-RSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsEcdhRsaWithCamellia128GcmSha256:
		return "ECDH-RSA-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsEcdhRsaWithCamellia256GcmSha384:
		return "ECDH-RSA-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsPskWithCamellia128GcmSha256:
		return "PSK-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsPskWithCamellia256GcmSha384:
		return "PSK-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsDhePskWithCamellia128GcmSha256:
		return "DHE-PSK-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsDhePskWithCamellia256GcmSha384:
		return "DHE-PSK-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsRsaPskWithCamellia128GcmSha256:
		return "RSA-PSK-WITH-CAMELLIA-128-GCM-SHA256"
	case CipherTlsRsaPskWithCamellia256GcmSha384:
		return "RSA-PSK-WITH-CAMELLIA-256-GCM-SHA384"
	case CipherTlsPskWithCamellia128CbcSha256:
		return "PSK-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsPskWithCamellia256CbcSha384:
		return "PSK-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsDhePskWithCamellia128CbcSha256:
		return "DHE-PSK-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsDhePskWithCamellia256CbcSha384:
		return "DHE-PSK-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsRsaPskWithCamellia128CbcSha256:
		return "RSA-PSK-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsRsaPskWithCamellia256CbcSha384:
		return "RSA-PSK-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsEcdhePskWithCamellia128CbcSha256:
		return "ECDHE-PSK-WITH-CAMELLIA-128-CBC-SHA256"
	case CipherTlsEcdhePskWithCamellia256CbcSha384:
		return "ECDHE-PSK-WITH-CAMELLIA-256-CBC-SHA384"
	case CipherTlsRsaWithAes128Ccm:
		return "RSA-WITH-AES-128-CCM"
	case CipherTlsRsaWithAes256Ccm:
		return "RSA-WITH-AES-256-CCM"
	case CipherTlsDheRsaWithAes128Ccm:
		return "DHE-RSA-WITH-AES-128-CCM"
	case CipherTlsDheRsaWithAes256Ccm:
		return "DHE-RSA-WITH-AES-256-CCM"
	case CipherTlsRsaWithAes128Ccm8:
		return "RSA-WITH-AES-128-CCM-8"
	case CipherTlsRsaWithAes256Ccm8:
		return "RSA-WITH-AES-256-CCM-8"
	case CipherTlsDheRsaWithAes128Ccm8:
		return "DHE-RSA-WITH-AES-128-CCM-8"
	case CipherTlsDheRsaWithAes256Ccm8:
		return "DHE-RSA-WITH-AES-256-CCM-8"
	case CipherTlsPskWithAes128Ccm:
		return "PSK-WITH-AES-128-CCM"
	case CipherTlsPskWithAes256Ccm:
		return "PSK-WITH-AES-256-CCM"
	case CipherTlsDhePskWithAes128Ccm:
		return "DHE-PSK-WITH-AES-128-CCM"
	case CipherTlsDhePskWithAes256Ccm:
		return "DHE-PSK-WITH-AES-256-CCM"
	case CipherTlsPskWithAes128Ccm8:
		return "PSK-WITH-AES-128-CCM-8"
	case CipherTlsPskWithAes256Ccm8:
		return "PSK-WITH-AES-256-CCM-8"
	case CipherTlsPskDheWithAes128Ccm8:
		return "PSK-DHE-WITH-AES-128-CCM-8"
	case CipherTlsPskDheWithAes256Ccm8:
		return "PSK-DHE-WITH-AES-256-CCM-8"
	case CipherTlsEcdheEcdsaWithAes128Ccm:
		return "ECDHE-ECDSA-WITH-AES-128-CCM"
	case CipherTlsEcdheEcdsaWithAes256Ccm:
		return "ECDHE-ECDSA-WITH-AES-256-CCM"
	case CipherTlsEcdheEcdsaWithAes128Ccm8:
		return "ECDHE-ECDSA-WITH-AES-128-CCM-8"
	case CipherTlsEcdheEcdsaWithAes256Ccm8:
		return "ECDHE-ECDSA-WITH-AES-256-CCM-8"
	case CipherTlsEccpwdWithAes128GcmSha256:
		return "ECCPWD-WITH-AES-128-GCM-SHA256"
	case CipherTlsEccpwdWithAes256GcmSha384:
		return "ECCPWD-WITH-AES-256-GCM-SHA384"
	case CipherTlsEccpwdWithAes128CcmSha256:
		return "ECCPWD-WITH-AES-128-CCM-SHA256"
	case CipherTlsEccpwdWithAes256CcmSha384:
		return "ECCPWD-WITH-AES-256-CCM-SHA384"
	case CipherTlsSha256Sha256:
		return "SHA256-SHA256"
	case CipherTlsSha384Sha384:
		return "SHA384-SHA384"
	case CipherTlsGostr341112256WithKuznyechikCtrOmac:
		return "GOSTR341112-256-WITH-KUZNYECHIK-CTR-OMAC"
	case CipherTlsGostr341112256WithMagmaCtrOmac:
		return "GOSTR341112-256-WITH-MAGMA-CTR-OMAC"
	case CipherTlsGostr341112256With28147CntImit:
		return "GOSTR341112-256-WITH-28147-CNT-IMIT"
	case CipherTlsGostr341112256WithKuznyechikMgmL:
		return "GOSTR341112-256-WITH-KUZNYECHIK-MGM-L"
	case CipherTlsGostr341112256WithMagmaMgmL:
		return "GOSTR341112-256-WITH-MAGMA-MGM-L"
	case CipherTlsGostr341112256WithKuznyechikMgmS:
		return "GOSTR341112-256-WITH-KUZNYECHIK-MGM-S"
	case CipherTlsGostr341112256WithMagmaMgmS:
		return "GOSTR341112-256-WITH-MAGMA-MGM-S"
	case CipherTlsEcdheRsaWithChacha20Poly1305Sha256:
		return "ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsEcdheEcdsaWithChacha20Poly1305Sha256:
		return "ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsDheRsaWithChacha20Poly1305Sha256:
		return "DHE-RSA-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsPskWithChacha20Poly1305Sha256:
		return "PSK-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsEcdhePskWithChacha20Poly1305Sha256:
		return "ECDHE-PSK-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsDhePskWithChacha20Poly1305Sha256:
		return "DHE-PSK-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsRsaPskWithChacha20Poly1305Sha256:
		return "RSA-PSK-WITH-CHACHA20-POLY1305-SHA256"
	case CipherTlsEcdhePskWithAes128GcmSha256:
		return "ECDHE-PSK-WITH-AES-128-GCM-SHA256"
	case CipherTlsEcdhePskWithAes256GcmSha384:
		return "ECDHE-PSK-WITH-AES-256-GCM-SHA384"
	case CipherTlsEcdhePskWithAes128Ccm8Sha256:
		return "ECDHE-PSK-WITH-AES-128-CCM-8-SHA256"
	case CipherTlsEcdhePskWithAes128CcmSha256:
		return "ECDHE-PSK-WITH-AES-128-CCM-SHA256"
	default:
		return fmt.Sprintf("UNKNOWN-%04x", *cipher)
	}
}
